POST http://localhost:3000/registerUser HTTP/1.1
content-type: application/json

{
    "name": "e",
    "email": "exae@example.com",
    "role": "user"
}
###

GET http://localhost:3000/user HTTP/1.1
content-type: application/json



###
GET https://fastify-server-app.herokuapp.com/novel HTTP/1.1
content-type: application/json

###

POST https://fastify-server-app.herokuapp.com/addNovel  HTTP/1.1
content-type: application/json

{
    "title": "Another title Posted By text.http",
    "user_id": 24,
    "summary": "Summary of the Novel",
    "age_restriction": "All"
}


###

POST https://fastify-server-app.herokuapp.com/novel  HTTP/1.1
content-type: application/json

{
    "text": "New text Posted By text.http",
    "episode_id": 24
}

###

POST http://localhost:3000/addEpisode HTTP/1.1
content-type: application/json

{
    "episode_title": "New Episode PekoPeko",
    "novel_id": 14
}